### PR TITLE
fixing citations when style is ieee

### PR DESCRIPTION
**Pull request by harmishhk**
corrects issue #7

### CODE REVIEW

**Comment by harmishhk** [comment]
As a side-effect, this fix allows to put `[#citation-style]: #ieee` anywhere in the file (relaxes ' _before_ any citations' requirement).

**Comment by harmishhk** [comment]
as a side-effect this fix allows to put `[#citation-style]: #ieee` anywhere in the file (relaxes '_before_ any citation' requirement).

ps: i closed the pr by mistake while commenting

**Comment by retorquere** [comment]
I don't think the relaxation holds; the bibliography was never vulnerable to placement, but the citations are.

**Comment by retorquere** [comment]
I've changed the plugin ti use [mdast.js](https://github.com/wooorm/mdast) for proper markdown parsing rather than regex'ing, but looking to re-apply your pull request, I don't understand what happens where it says

```
-      # number the citations when style is ieee
-      if @style == 'ieee'
-        bib = bib.replace(/\[([^\]]*)\][^]*?a>/g, (match, key) => (match + @citations[key.substring(1)] + ' '))
-      editor.setTextInBufferRange(bibliography, "[#bibliography]: #start\n#{bib.replace(/\n$/, '')}\n[#bibliography]: #end\n") if bib
```

can you walk me through this, or alternately, I walk you throug the mdast filter I added?

**Comment by harmishhk** [comment]
Since in the [IEEE style](http://www.ieee.org/documents/ieeecitationref.pdf), the references in the text are just a number like `[1]`, it is necessary to put these reference number before each citation in the bibliography section. 

For example, for following markdown text
```
In crowd simulation literature [\[3\]][@park_cav_2013], there exist ...
```
respective bibliography entry should be of the form
```
[@park_cav_2013]: #park_cav_2013 "Park, J. H., Rojas, F. A., & Yang, H. S. (2013). A collision avoidance behavior model for crowd simulation based on psychological findings. _Computer Animation and Virtual Worlds_, _24_(3-4), 173–183."
<a name="park_cav_2013"></a> \[3\] Park, J. H., Rojas, F. A., & Yang, H. S. \(2013\). A collision avoidance behavior model for crowd simulation based on psychological findings. _Computer Animation and Virtual Worlds_, _24_\(3\-4\), 173–183.
```
note the `\[3\]` after `<a name="park_cav_2013"></a>` and before the entry text.

The response to the `POST` request to Zotero in the `bibliography` function, however, does not include these reference number before each citation. Therefore I had to put the respective citation number in front of each bibliography entry by looking into the `@citations` dictionary. The third line in your quoted text accomplishes exactly this with the `bib.replace` function. Where the first group of the regex gives citation key which is then used to retrieve the citation number from the `@citations` dictionary and this number (of the form `\[3\]`) is added just before the bibliography entry.

Hope, this makes it clear. In any case, please go ahead with the [mdast.js](https://github.com/wooorm/mdast) based parsing even IEEE style does not work as expected initially, I can try to adapt it later.

PS: by the way, I have noticed that also while using other number based citation styles like `Nature` there is no number returned in the bibliography.

**Comment by retorquere** [comment]
Looks like it currently Just Works, although I have no idea how this particular change could have affected this. If I push this:
```
[??][@bentley_academic_2011]

[][@TayEA11]
[](@TayEA11,@CumEA14)
[](@tayea11)

[\(Latour, 2005/2008\)][@latour_ny_2008]

[#citation-style]: #ieee
[#bibliography]: #start
[@latour_ny_2008]: #latour_ny_2008 "Latour, B. (2008). _En ny sociologi for et nyt samfund. Introduktion til Aktør-Netværk-Teori_. København: Akademisk Forlag. (Original work published 2005)"
<a name="latour_ny_2008"></a>Latour, B. \(2008\). _En ny sociologi for et nyt samfund. Introduktion til Aktør\-Netværk\-Teori_. København: Akademisk Forlag. \(Original work published 2005\)
[#bibliography]: #end
```

through, I get

```
[??][@bentley_academic_2011]

[??][@tayea11]
[\[1\], \[2\]](@TayEA11,@CumEA14)
[??](@tayea11)

[??][@latour_ny_2008]

[#citation-style]: #ieee

[#bibliography]: #start

[@tayea11]: #TayEA11 "[1]K. E. Taylor, R. J. Stouffer, and G. A. Meehl, “An Overview of CMIP5 and the Experiment Design,” _Bulletin of the American Meteorological Society_, vol. 93, pp. 485–498, Oct. 2011."

<a name="TayEA11"></a>\[1\]K. E. Taylor, R. J. Stouffer, and G. A. Meehl, “An Overview of CMIP5 and the Experiment Design,” _Bulletin of the American Meteorological Society_, vol. 93, pp. 485–498, Oct. 2011.

[@cumea14]: #CumEA14 "[2]B. Cumming, G. Fourestey, O. Fuhrer, T. Gysi, M. Fatica, and T. C. Schulthess, “Application Centric Energy-efficiency Study of Distributed Multi-core and Hybrid CPU-GPU Systems,” in _Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis_, Piscataway, NJ, USA, 2014, pp. 819–829."

<a name="CumEA14"></a>\[2\]B. Cumming, G. Fourestey, O. Fuhrer, T. Gysi, M. Fatica, and T. C. Schulthess, “Application Centric Energy\-efficiency Study of Distributed Multi\-core and Hybrid CPU\-GPU Systems,” in _Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis_, Piscataway, NJ, USA, 2014, pp. 819–829.

[#bibliography]: #end
```

**Comment by harmishhk** [comment]
Looks fine to me. Also don't know how same `POST` request gives you the proper response. Maybe I have some problem at zotero/better-bibtex side, I'll check that.

**Comment by retorquere** [comment]
Let me just cut 1.4.3 first -- best to work from that.

**Comment by retorquere** [comment]
OK, I've published both a new BBT and a new Atom package -- could you have a look? I think it does what you want it to. The new parser should make things vastly more robust, although it does introduce a few unfortunate side-effects; it is opinionated about how the re-constructed markdown should look. For fairly good reasons, but it's sure to upset some people.

**Comment by harmishhk** [comment]
Yes, now the `POST` request returns properly formatted bibliography with correct numbers. The `test.md` is modified as you mentioned earlier.

However, the same effect as of issue #7 is there again. When using multiple citations on different lines the returned number inside text link is always set to `[1]`. For example, if I put this
```
[][@hicheur_nl_2005]
[][@hollands_ebr_2002]

[#citation-style]: #ieee
[#bibliography]: #
```
I get
```
[\[1\]][@hicheur_nl_2005]
[\[1\]][@hollands_ebr_2002]

[#citation-style]: #ieee

[#bibliography]: #start

[@hicheur_nl_2005]: #hicheur_nl_2005 "[1]H. Hicheur, S. Vieilledent, and A. Berthoz, “Head motion in humans alternating between straight and curved walking path: Combination of stabilizing and anticipatory orienting mechanisms,” _Neuroscience Letters_, vol. 383, no. 1–2, pp. 87–92, 2005."

<a name="hicheur_nl_2005"></a>\[1\]H. Hicheur, S. Vieilledent, and A. Berthoz, “Head motion in humans alternating between straight and curved walking path: Combination of stabilizing and anticipatory orienting mechanisms,” _Neuroscience Letters_, vol. 383, no. 1–2, pp. 87–92, 2005.

[@hollands_ebr_2002]: #hollands_ebr_2002 "[2]M. A. Hollands, A. E. Patla, and J. N. Vickers, “‘Look where you’re going!’: gaze behaviour associated with maintaining and changing the direction of locomotion,” _Experimental Brain Research_, vol. 143, no. 2, pp. 221–230, 2002."

<a name="hollands_ebr_2002"></a>\[2\]M. A. Hollands, A. E. Patla, and J. N. Vickers, “‘Look where you’re going\!’: gaze behaviour associated with maintaining and changing the direction of locomotion,” _Experimental Brain Research_, vol. 143, no. 2, pp. 221–230, 2002.

[#bibliography]: #end
```

Last time I solved this issue by walking two times over the buffer. At fist walk just collect the citation keys in the `citations` dictionary, then call `citation` method with all the keys (comma separated), finally reassign values in the `citations` dictionary. Modifications in the buffer are done only at second walk. At second walk, we will always return correct number for citation item from the `citations` dictionary. So, I think similar fix is needed here.

There is also one catch: BBT does not return `??` when a citation is not found. So, in fact, I needed to call BBT with each key as I find them during the first walk as well, just to register a `??` in the `citations` dictionary. If it is feasible at BBT side to return a `??` when a key is not found, then this additional exercise is not required. For example posting `["hicheur_nl_2005", "hollands_ebr_2002", "some"]` as params to BBT with `citation` method would return `"\\[1\\], \\[2\\], ??"` instead of `"\\[1\\], \\[2\\]"`.

**Comment by retorquere** [comment]
I think I must hand them to the processor all at once - working on it.

**Comment by retorquere** [comment]
Try 0.11 + BBT 1.4.5

**Comment by harmishhk** [comment]
Works very nicely now :)

Thanks for the fast updates. Appreciate your work.

**Comment by retorquere** [comment]
Hmm, I don't think it does the '??'  thing for multi-references. That's nasty -  I'll see what I can do about that.

**Pull request merged**
